spring:
  application:
    name: AlinOnline
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/alin_online?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull
    username: root
    password: password
mybatis:
  #指定全局配置文件的位置
  mapper-locations: classpath:mapper/*Mapper.xml

---
spring:
  application:
    name: AlinOnline
  profiles: dev
server:
  port: 8083
#debug: true

---
server:
  port: 8080
spring:
  profiles: prod # 指定属于哪个环境
logging:
  file:
    path: /alin_online/logs
